advanced_models:
  gb_learning_rate: 0.1
  gb_max_depth: 5
  gb_n_estimators: 300
  rf_max_depth: 15
  rf_min_samples_split: 2
  rf_n_estimators: 300
baseline_models:
  arima_order:
    - 1
    - 1
    - 1
data_paths:
  base_dir: data
  output_dir: processed_data
  processed_dir: processed_data
data_validation:
  max_date: '2022-12-31'
  min_date: '1965-01-01'
  min_rows: 1000
  required_columns:
    - country
    - year
    - renewable_generation
    - total_energy_consumption
feature_engineering:
  create_weather_features: true
  renewable_cols:
    - hydro_generation
    - solar_generation
    - wind_generation
  total_energy_col: total_energy_consumption
model_paths:
  output_dir: models
preprocessing:
  categorical_missing_strategy: mode
  date_column: year
  group_column: country
  handle_missing: true
  lag_periods:
    - 1
    - 3
    - 6
    - 12
  normalization_method: standard
  normalize: true
  numeric_missing_strategy: knn
  outlier_method: iqr
  outlier_threshold: 3.0
  remove_outliers: true
  rolling_windows:
    - 3
    - 6
    - 12
  target_column: renewable_generation
training:
  feature_columns:
    - renewable_generation_rolling_mean_3
    - renewable_generation_lag_1
    - renewable_generation_rolling_mean_6
    - renewable_generation_rolling_mean_12
    - renewable_generation_lag_3
    - hydro_generation
    - biofuel_generation
    - solar_generation
  random_state: 42
  target_column: renewable_generation
  test_size: 0.2
  time_column: year
  tune_hyperparameters: true
