data_paths:
  base_dir: data
  output_dir: processed_data
data_validation:
  max_date: '2022-12-31'
  min_date: '1965-01-01'
  min_rows: 1000
  required_columns:
  - country
  - year
  - renewable_generation
  - total_energy_consumption
feature_engineering:
  create_weather_features: true
  renewable_cols:
  - hydro_generation
  - solar_generation
  - wind_generation
  total_energy_col: total_energy_consumption
preprocessing:
  categorical_missing_strategy: mode
  date_column: year
  group_column: country
  handle_missing: true
  lag_periods:
  - 1
  - 3
  - 6
  - 12
  normalization_method: standard
  normalize: true
  numeric_missing_strategy: knn
  outlier_method: iqr
  outlier_threshold: 3.0
  remove_outliers: true
  rolling_windows:
  - 3
  - 6
  - 12
  target_column: renewable_generation
