advanced_models:
  gb_learning_rate: 0.1
  gb_max_depth: 5
  gb_n_estimators: 300
  rf_max_depth: 15
  rf_min_samples_split: 2
  rf_n_estimators: 300
baseline_models:
  arima_order:
  - 1
  - 1
  - 1
  lasso_alpha: 0.1
  ridge_alpha: 1.0
data_paths:
  base_dir: data
  output_dir: processed_data
  processed_dir: processed_data
data_validation:
  max_date: '2022-12-31'
  min_date: '1965-01-01'
  min_rows: 1000
  required_columns:
  - Year
  - Month
  - Total Renewable Energy
feature_engineering:
  create_weather_features: true
  renewable_cols:
  - Hydroelectric Power
  - Solar Energy
  - Wind Energy
  total_energy_col: Total Renewable Energy
model_paths:
  output_dir: models
preprocessing:
  categorical_missing_strategy: mode
  date_column: Year
  group_column: Month
  handle_missing: true
  lag_periods:
  - 1
  - 3
  - 6
  - 12
  normalization_method: standard
  normalize: true
  numeric_missing_strategy: knn
  outlier_method: iqr
  outlier_threshold: 3.0
  remove_outliers: true
  rolling_windows:
  - 3
  - 6
  - 12
  target_column: Total Renewable Energy
training:
  feature_columns:
  - Hydroelectric Power
  - Solar Energy
  - Wind Energy
  - Geothermal Energy
  - Biomass Energy
  random_state: 42
  target_column: Total Renewable Energy
  test_size: 0.2
  time_column: Year
  tune_hyperparameters: true
