data_paths:
  base_dir: data
  processed_dir: processed_data
  output_dir: processed_data

data_validation:
  required_columns:
    - Year
    - Month
    - Total Renewable Energy
  min_rows: 1000
  min_date: '1965-01-01'
  max_date: '2022-12-31'

preprocessing:
  handle_missing: true
  numeric_missing_strategy: 'knn'
  categorical_missing_strategy: 'mode'
  remove_outliers: true
  outlier_method: 'iqr'
  outlier_threshold: 3.0
  date_column: 'Year'
  target_column: 'Total Renewable Energy'
  lag_periods: [ 1, 3, 6, 12 ]
  rolling_windows: [ 3, 6, 12 ]
  group_column: 'Month'
  normalize: true
  normalization_method: 'standard'

feature_engineering:
  create_weather_features: true
  renewable_cols:
    - 'Hydroelectric Power'
    - 'Solar Energy'
    - 'Wind Energy'
  total_energy_col: 'Total Renewable Energy'

model_paths:
  output_dir: models

training:
  tune_hyperparameters: true
  test_size: 0.2
  random_state: 42
  target_column: 'Total Renewable Energy'
  time_column: 'Year'
  feature_columns:
    - 'Hydroelectric Power'
    - 'Solar Energy'
    - 'Wind Energy'
    - 'Geothermal Energy'
    - 'Biomass Energy'

baseline_models:
  arima_order: [ 1, 1, 1 ]
  ridge_alpha: 1.0
  lasso_alpha: 0.1

advanced_models:
  rf_n_estimators: 300
  rf_max_depth: 10
  rf_min_samples_split: 2
  gb_n_estimators: 300
  gb_max_depth: 4
  gb_learning_rate: 0.1
  svr_C: 1.0
  svr_kernel: 'rbf'