data_paths:
  base_dir: data
  processed_dir: processed_data
  output_dir: processed_data

data_validation:
  required_columns:
    - country
    - year
    - renewable_generation
    - total_energy_consumption
  min_rows: 1000
  min_date: '1965-01-01'
  max_date: '2022-12-31'

preprocessing:
  handle_missing: true
  numeric_missing_strategy: 'knn'
  categorical_missing_strategy: 'mode'
  remove_outliers: true
  outlier_method: 'iqr'
  outlier_threshold: 3.0
  date_column: 'year'
  target_column: 'renewable_generation'
  lag_periods: [ 1, 3, 6, 12 ]
  rolling_windows: [ 3, 6, 12 ]
  group_column: 'country'
  normalize: true
  normalization_method: 'standard'

feature_engineering:
  create_weather_features: true
  renewable_cols:
    - hydro_generation
    - solar_generation
    - wind_generation
  total_energy_col: total_energy_consumption

model_paths:
  output_dir: models

training:
  tune_hyperparameters: true
  test_size: 0.2
  random_state: 42
  target_column: renewable_generation
  time_column: year
  feature_columns:
    - hydro_generation
    - biofuel_generation
    - solar_generation
    - geothermal_generation
    - total_energy_consumption
    - renewable_share_pct
    - wind_generation
    - renewable_generation_lag_1
    - renewable_generation_lag_3
    - renewable_generation_rolling_mean_3
    - renewable_generation_rolling_mean_6

baseline_models:
  arima_order: [ 1, 1, 1 ]